<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MCPHub.Core</RootNamespace>
    <AssemblyName>MCPHub.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\MCPHub.Processes\MCPHub.Processes.csproj" />
    <ProjectReference Include="..\MCPHub.Proxy\MCPHub.Proxy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Semver" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

</Project>
