<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MCPHub.Proxy</RootNamespace>
    <AssemblyName>MCPHub.Proxy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

</Project>
